/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AvailabilityRule - The rules for an availability schedule.
 */
public class AvailabilityRule {
    /**
     * A specific date in the future that this should be applied to (i.e. "2030-12-31").
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("date")public String date;
    public AvailabilityRule withDate(String date) {
        this.date = date;
        return this;
    }
    
    /**
     * The intervals to be applied to this Rule. Each interval represents when booking a meeting is allowed. If the interval array is empty, then there is no booking availability for that day. Time is in 24h format (i.e. "17:30") and local to the timezone in the Availability Schedule.
     */
    @JsonProperty("intervals")public AvailabilityRuleIntervals[] intervals;
    public AvailabilityRule withIntervals(AvailabilityRuleIntervals[] intervals) {
        this.intervals = intervals;
        return this;
    }
    
    /**
     * The type of this Availability Rule; can be "wday" or a specific "date".
     */
    @JsonProperty("type")public AvailabilityRuleTypeEnum type;
    public AvailabilityRule withType(AvailabilityRuleTypeEnum type) {
        this.type = type;
        return this;
    }
    
    /**
     * The day of the week for which this Rule should be applied to.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("wday")public AvailabilityRuleWdayEnum wday;
    public AvailabilityRule withWday(AvailabilityRuleWdayEnum wday) {
        this.wday = wday;
        return this;
    }
    
}
