/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AvailabilitySchedule - The availability schedule set by the user.
 */
public class AvailabilitySchedule {
    /**
     * This is the default Availability Schedule in use.
     */
    @JsonProperty("default")
    public Boolean default_;
    public AvailabilitySchedule withDefault(Boolean default_) {
        this.default_ = default_;
        return this;
    }
    
    /**
     * The name of this Availability Schedule.
     */
    @JsonProperty("name")
    public String name;
    public AvailabilitySchedule withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * The rules of this Availability Schedule.
     */
    @JsonProperty("rules")
    public AvailabilityRule[] rules;
    public AvailabilitySchedule withRules(AvailabilityRule[] rules) {
        this.rules = rules;
        return this;
    }
    
    /**
     * The timezone for which this Availability Schedule is originated in.
     */
    @JsonProperty("timezone")
    public String timezone;
    public AvailabilitySchedule withTimezone(String timezone) {
        this.timezone = timezone;
        return this;
    }
    
    /**
     * A URI reference to this Availability Schedule.
     */
    @JsonProperty("uri")
    public String uri;
    public AvailabilitySchedule withUri(String uri) {
        this.uri = uri;
        return this;
    }
    
    /**
     * A URI reference to a User.
     */
    @JsonProperty("user")
    public String user;
    public AvailabilitySchedule withUser(String user) {
        this.user = user;
        return this;
    }
    
}
