/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CustomLocation - Use this to describe an existing Calendly-supported event location.
 */
public class CustomLocation {
    /**
     * The location description provided by the event host (publisher)
     */
    @JsonProperty("location")public String location;
    public CustomLocation withLocation(String location) {
        this.location = location;
        return this;
    }
    
    /**
     * The event location doesn't fall into a standard category defined by the event host (publisher)
     */
    @JsonProperty("type")public CustomLocationTypeEnum type;
    public CustomLocation withType(CustomLocationTypeEnum type) {
        this.type = type;
        return this;
    }
    
}
