/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class EventInviteesCounter {
    /**
     * Total invitees for an event that have not canceled
     */
    @JsonProperty("active")public Double active;
    public EventInviteesCounter withActive(Double active) {
        this.active = active;
        return this;
    }
    
    /**
     * Maximum number of active invitees that can book the event
     */
    @JsonProperty("limit")public Double limit;
    public EventInviteesCounter withLimit(Double limit) {
        this.limit = limit;
        return this;
    }
    
    /**
     * Total invitees for an event, including invitees that have canceled
     */
    @JsonProperty("total")public Double total;
    public EventInviteesCounter withTotal(Double total) {
        this.total = total;
        return this;
    }
    
}
