/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import calendly.calendly.utils.DateTimeDeserializer;
import calendly.calendly.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

/**
 * EventTypeAvailableTime - An available meeting time slot for the given event type
 */
public class EventTypeAvailableTime {
    /**
     * Total remaining invitees for this available time. For Group Event Type, more than one invitee can book in this available time. For all other Event Types, only one invitee can book in this available time.
     */
    @JsonProperty("invitees_remaining")
    public Double inviteesRemaining;
    public EventTypeAvailableTime withInviteesRemaining(Double inviteesRemaining) {
        this.inviteesRemaining = inviteesRemaining;
        return this;
    }
    
    /**
     * The URL of the user\u2019s scheduling site where invitees book this event type
     */
    @JsonProperty("scheduling_url")
    public String schedulingUrl;
    public EventTypeAvailableTime withSchedulingUrl(String schedulingUrl) {
        this.schedulingUrl = schedulingUrl;
        return this;
    }
    
    /**
     * The moment the event was scheduled to start in UTC time
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("start_time")
    public OffsetDateTime startTime;
    public EventTypeAvailableTime withStartTime(OffsetDateTime startTime) {
        this.startTime = startTime;
        return this;
    }
    
    /**
     * Indicates that the open time slot is "available"
     */
    @JsonProperty("status")
    public String status;
    public EventTypeAvailableTime withStatus(String status) {
        this.status = status;
        return this;
    }
    
}
