/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * EventTypeKindDescriptionEnum - A formatted description of the kind of event type.
 */
public enum EventTypeKindDescriptionEnum {
    COLLECTIVE("Collective"),
    GROUP("Group"),
    ONE_ON_ONE("One-on-One"),
    ROUND_ROBIN("Round Robin");

    @JsonValue
    public final String value;

    private EventTypeKindDescriptionEnum(String value) {
        this.value = value;
    }
}
