/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class EventEventMemberships {
    /**
     * Canonical reference (unique identifier) for the user
     */
    @JsonProperty("user")
    public String user;
    public EventEventMemberships withUser(String user) {
        this.user = user;
        return this;
    }
    
}
