/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * EventTypeCustomQuestionTypeEnum - The type of response that the invitee provides to the custom question; can be one or multiple lines of text, a phone number, or single- or multiple-select.
 */
public enum EventTypeCustomQuestionTypeEnum {
    STRING("string"),
    TEXT("text"),
    PHONE_NUMBER("phone_number"),
    SINGLE_SELECT("single_select"),
    MULTI_SELECT("multi_select");

    @JsonValue
    public final String value;

    private EventTypeCustomQuestionTypeEnum(String value) {
        this.value = value;
    }
}
