/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * EventTypeKindEnum - Indicates if the event type is "solo" (belongs to an individual user) or "group"
 */
public enum EventTypeKindEnum {
    SOLO("solo"),
    GROUP("group");

    @JsonValue
    public final String value;

    private EventTypeKindEnum(String value) {
        this.value = value;
    }
}
