/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import calendly.calendly.utils.DateTimeDeserializer;
import calendly.calendly.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

/**
 * EventType - A configuration for an Event
 */
public class EventType {
    /**
     * Indicates if the event is active or not.
     */
    @JsonProperty("active")
    public Boolean active;
    public EventType withActive(Boolean active) {
        this.active = active;
        return this;
    }
    
    /**
     * Indicates if this event type is managed by an organization admin
     */
    @JsonProperty("admin_managed")
    public Boolean adminManaged;
    public EventType withAdminManaged(Boolean adminManaged) {
        this.adminManaged = adminManaged;
        return this;
    }
    
    /**
     * Indicates if the event type is for a poll or an instant booking
     */
    @JsonProperty("booking_method")
    public EventTypeBookingMethodEnum bookingMethod;
    public EventType withBookingMethod(EventTypeBookingMethodEnum bookingMethod) {
        this.bookingMethod = bookingMethod;
        return this;
    }
    
    /**
     * The hexadecimal color value of the event type's scheduling page
     */
    @JsonProperty("color")
    public String color;
    public EventType withColor(String color) {
        this.color = color;
        return this;
    }
    
    /**
     * The moment the event type was created (e.g. "2020-01-02T03:04:05.678123Z")
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created_at")
    public OffsetDateTime createdAt;
    public EventType withCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }
    
    @JsonProperty("custom_questions")
    public EventTypeCustomQuestion[] customQuestions;
    public EventType withCustomQuestions(EventTypeCustomQuestion[] customQuestions) {
        this.customQuestions = customQuestions;
        return this;
    }
    
    /**
     * The moment the event type was deleted (e.g. "2020-01-02T03:04:05.678123Z"). Since event types can be deleted but their scheduled events remain it's useful to fetch a deleted event type when you still require event type data for a scheduled event.
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("deleted_at")
    public OffsetDateTime deletedAt;
    public EventType withDeletedAt(OffsetDateTime deletedAt) {
        this.deletedAt = deletedAt;
        return this;
    }
    
    /**
     * The event type's description (formatted with HTML)
     */
    @JsonProperty("description_html")
    public String descriptionHtml;
    public EventType withDescriptionHtml(String descriptionHtml) {
        this.descriptionHtml = descriptionHtml;
        return this;
    }
    
    /**
     * The event type's description (in non formatted text)
     */
    @JsonProperty("description_plain")
    public String descriptionPlain;
    public EventType withDescriptionPlain(String descriptionPlain) {
        this.descriptionPlain = descriptionPlain;
        return this;
    }
    
    /**
     * The length of sessions booked with this event type
     */
    @JsonProperty("duration")
    public Double duration;
    public EventType withDuration(Double duration) {
        this.duration = duration;
        return this;
    }
    
    /**
     * Contents of a note that may be associated with the event type
     */
    @JsonProperty("internal_note")
    public String internalNote;
    public EventType withInternalNote(String internalNote) {
        this.internalNote = internalNote;
        return this;
    }
    
    /**
     * Indicates if the event type is "solo" (belongs to an individual user) or "group"
     */
    @JsonProperty("kind")
    public EventTypeKindEnum kind;
    public EventType withKind(EventTypeKindEnum kind) {
        this.kind = kind;
        return this;
    }
    
    /**
     * A formatted description of the kind of event type.
     */
    @JsonProperty("kind_description")
    public EventTypeKindDescriptionEnum kindDescription;
    public EventType withKindDescription(EventTypeKindDescriptionEnum kindDescription) {
        this.kindDescription = kindDescription;
        return this;
    }
    
    /**
     * The event type name (in human-readable format)
     */
    @JsonProperty("name")
    public String name;
    public EventType withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * Indicates if the event type is "round robin" (alternates between hosts) or "collective" (invitees pick a time when all participants are available) or "null" (the event type doesn\u2019t consider the availability of a group participants)
     */
    @JsonProperty("pooling_type")
    public EventTypePoolingTypeEnum poolingType;
    public EventType withPoolingType(EventTypePoolingTypeEnum poolingType) {
        this.poolingType = poolingType;
        return this;
    }
    
    /**
     * The publicly visible profile of a User or a Team that's associated with the Event Type (note: some Event Types don't have profiles)
     */
    @JsonProperty("profile")
    public Profile profile;
    public EventType withProfile(Profile profile) {
        this.profile = profile;
        return this;
    }
    
    /**
     * The URL of the user\u2019s scheduling site where invitees book this event type
     */
    @JsonProperty("scheduling_url")
    public String schedulingUrl;
    public EventType withSchedulingUrl(String schedulingUrl) {
        this.schedulingUrl = schedulingUrl;
        return this;
    }
    
    /**
     * Indicates if the event type is hidden on the owner's main scheduling page
     */
    @JsonProperty("secret")
    public Boolean secret;
    public EventType withSecret(Boolean secret) {
        this.secret = secret;
        return this;
    }
    
    /**
     * The portion of the event type's URL that identifies a specific web page (in a human-readable format)
     */
    @JsonProperty("slug")
    public String slug;
    public EventType withSlug(String slug) {
        this.slug = slug;
        return this;
    }
    
    /**
     * Indicates if the event type is "AdhocEventType" (ad hoc event) or "StandardEventType" (standard event type)
     */
    @JsonProperty("type")
    public EventTypeTypeEnum type;
    public EventType withType(EventTypeTypeEnum type) {
        this.type = type;
        return this;
    }
    
    /**
     * The moment the event type was last updated (e.g. "2020-01-02T03:04:05.678123Z")
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated_at")
    public OffsetDateTime updatedAt;
    public EventType withUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }
    
    /**
     * Canonical reference (unique identifier) for the event type
     */
    @JsonProperty("uri")
    public String uri;
    public EventType withUri(String uri) {
        this.uri = uri;
        return this;
    }
    
}
