/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * EventStatusEnum - Indicates if the event is "active" or "canceled"
 */
public enum EventStatusEnum {
    ACTIVE("active"),
    CANCELED("canceled");

    @JsonValue
    public final String value;

    private EventStatusEnum(String value) {
        this.value = value;
    }
}
