/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import calendly.calendly.utils.DateTimeDeserializer;
import calendly.calendly.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

/**
 * Event - Information about a scheduled meeting
 */
public class Event {
    /**
     * Information about the calendar event from the calendar provider.
     */
    @JsonProperty("calendar_event")public LegacyCalendarEvent calendarEvent;
    public Event withCalendarEvent(LegacyCalendarEvent calendarEvent) {
        this.calendarEvent = calendarEvent;
        return this;
    }
    
    /**
     * Provides data pertaining to the cancellation of the Event
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cancellation")public Cancellation cancellation;
    public Event withCancellation(Cancellation cancellation) {
        this.cancellation = cancellation;
        return this;
    }
    
    /**
     * The moment when the event was created (e.g. "2020-01-02T03:04:05.678123Z")
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created_at")public OffsetDateTime createdAt;
    public Event withCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }
    
    /**
     * The moment the event was scheduled to end in UTC time (e.g. "2020-01-02T03:04:05.678123Z")
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("end_time")public OffsetDateTime endTime;
    public Event withEndTime(OffsetDateTime endTime) {
        this.endTime = endTime;
        return this;
    }
    
    /**
     * Additional people added to an event by an invitee
     */
    @JsonProperty("event_guests")public Guest[] eventGuests;
    public Event withEventGuests(Guest[] eventGuests) {
        this.eventGuests = eventGuests;
        return this;
    }
    
    /**
     * Event membership list
     */
    @JsonProperty("event_memberships")public EventEventMemberships[] eventMemberships;
    public Event withEventMemberships(EventEventMemberships[] eventMemberships) {
        this.eventMemberships = eventMemberships;
        return this;
    }
    
    /**
     * The event type associated with this event
     */
    @JsonProperty("event_type")public String eventType;
    public Event withEventType(String eventType) {
        this.eventType = eventType;
        return this;
    }
    
    @JsonProperty("invitees_counter")public EventInviteesCounter inviteesCounter;
    public Event withInviteesCounter(EventInviteesCounter inviteesCounter) {
        this.inviteesCounter = inviteesCounter;
        return this;
    }
    
    /**
     * The polymorphic base type for an event location that Calendly supports
     */
    @JsonProperty("location")public Object location;
    public Event withLocation(Object location) {
        this.location = location;
        return this;
    }
    
    /**
     * The event name
     */
    @JsonProperty("name")public String name;
    public Event withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * The moment the event was scheduled to start in UTC time (e.g. "2020-01-02T03:04:05.678123Z").
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("start_time")public OffsetDateTime startTime;
    public Event withStartTime(OffsetDateTime startTime) {
        this.startTime = startTime;
        return this;
    }
    
    /**
     * Indicates if the event is "active" or "canceled"
     */
    @JsonProperty("status")public EventStatusEnum status;
    public Event withStatus(EventStatusEnum status) {
        this.status = status;
        return this;
    }
    
    /**
     * The moment when the event was last updated (e.g. "2020-01-02T03:04:05.678123Z")
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated_at")public OffsetDateTime updatedAt;
    public Event withUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }
    
    /**
     * Canonical reference (unique identifier) for the resource
     */
    @JsonProperty("uri")public String uri;
    public Event withUri(String uri) {
        this.uri = uri;
        return this;
    }
    
}
