/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GoogleConferenceTypeEnum - The event location is a Google Meet or Hangouts conference
 */
public enum GoogleConferenceTypeEnum {
    GOOGLE_CONFERENCE("google_conference");

    @JsonValue
    public final String value;

    private GoogleConferenceTypeEnum(String value) {
        this.value = value;
    }
}
