/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GoogleConference - Details about an Event that will take place using a Google Meet / Hangout conference
 */
public class GoogleConference {
    /**
     * Google conference meeting url
     */
    @JsonProperty("join_url")public String joinUrl;
    public GoogleConference withJoinUrl(String joinUrl) {
        this.joinUrl = joinUrl;
        return this;
    }
    
    /**
     * Indicates the current status of the Google conference
     */
    @JsonProperty("status")public GoogleConferenceStatusEnum status;
    public GoogleConference withStatus(GoogleConferenceStatusEnum status) {
        this.status = status;
        return this;
    }
    
    /**
     * The event location is a Google Meet or Hangouts conference
     */
    @JsonProperty("type")public GoogleConferenceTypeEnum type;
    public GoogleConference withType(GoogleConferenceTypeEnum type) {
        this.type = type;
        return this;
    }
    
}
