/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GotoMeetingConferenceTypeEnum - The event location is a GoToMeeting conference
 */
public enum GotoMeetingConferenceTypeEnum {
    GOTOMEETING("gotomeeting");

    @JsonValue
    public final String value;

    private GotoMeetingConferenceTypeEnum(String value) {
        this.value = value;
    }
}
