/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GotoMeetingConference - Details about an Event that will take place using a GotoMeeting conference
 */
public class GotoMeetingConference {
    /**
     * The conference metadata supplied by GoToMeeting
     */
    @JsonProperty("data")
    public GotoMeetingConferenceData data;
    public GotoMeetingConference withData(GotoMeetingConferenceData data) {
        this.data = data;
        return this;
    }
    
    /**
     * GoToMeeting conference meeting url
     */
    @JsonProperty("join_url")
    public String joinUrl;
    public GotoMeetingConference withJoinUrl(String joinUrl) {
        this.joinUrl = joinUrl;
        return this;
    }
    
    /**
     * Indicates the current status of the GoToMeeting conference
     */
    @JsonProperty("status")
    public GotoMeetingConferenceStatusEnum status;
    public GotoMeetingConference withStatus(GotoMeetingConferenceStatusEnum status) {
        this.status = status;
        return this;
    }
    
    /**
     * The event location is a GoToMeeting conference
     */
    @JsonProperty("type")
    public GotoMeetingConferenceTypeEnum type;
    public GotoMeetingConference withType(GotoMeetingConferenceTypeEnum type) {
        this.type = type;
        return this;
    }
    
}
