/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GotoMeetingConferenceStatusEnum - Indicates the current status of the GoToMeeting conference
 */
public enum GotoMeetingConferenceStatusEnum {
    INITIATED("initiated"),
    PROCESSING("processing"),
    PUSHED("pushed"),
    FAILED("failed");

    @JsonValue
    public final String value;

    private GotoMeetingConferenceStatusEnum(String value) {
        this.value = value;
    }
}
