/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * InboundCall - Invitee will call meeting publisher at the specified phone number
 */
public class InboundCall {
    /**
     * The phone number the invitee will use to call the event host (publisher)
     */
    @JsonProperty("location")public String location;
    public InboundCall withLocation(String location) {
        this.location = location;
        return this;
    }
    
    /**
     * 	
     * Indicates that the invitee will call the event host
     */
    @JsonProperty("type")public InboundCallTypeEnum type;
    public InboundCall withType(InboundCallTypeEnum type) {
        this.type = type;
        return this;
    }
    
}
