/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * InboundCallTypeEnum - 	
 * Indicates that the invitee will call the event host
 */
public enum InboundCallTypeEnum {
    INBOUND_CALL("inbound_call");

    @JsonValue
    public final String value;

    private InboundCallTypeEnum(String value) {
        this.value = value;
    }
}
