/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * InviteeSpecifiedLocationTypeEnum - The event location selected by the invitee
 */
public enum InviteeSpecifiedLocationTypeEnum {
    ASK_INVITEE("ask_invitee");

    @JsonValue
    public final String value;

    private InviteeSpecifiedLocationTypeEnum(String value) {
        this.value = value;
    }
}
