/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * InviteePaymentProviderEnum - Payment provider
 */
public enum InviteePaymentProviderEnum {
    STRIPE("stripe"),
    PAYPAL("paypal");

    @JsonValue
    public final String value;

    private InviteePaymentProviderEnum(String value) {
        this.value = value;
    }
}
