/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * InviteeQuestionAndAnswer - A response to a question on a booking page form
 */
public class InviteeQuestionAndAnswer {
    /**
     * The invitee's answer to the question
     */
    @JsonProperty("answer")public String answer;
    public InviteeQuestionAndAnswer withAnswer(String answer) {
        this.answer = answer;
        return this;
    }
    
    /**
     * The position of the question in relation to others on the booking form
     */
    @JsonProperty("position")public Double position;
    public InviteeQuestionAndAnswer withPosition(Double position) {
        this.position = position;
        return this;
    }
    
    /**
     * A question on the invitee's booking form
     */
    @JsonProperty("question")public String question;
    public InviteeQuestionAndAnswer withQuestion(String question) {
        this.question = question;
        return this;
    }
    
}
