/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * InviteePayment - Invitee payment
 */
public class InviteePayment {
    /**
     * The amount of the payment
     */
    @JsonProperty("amount")
    public Float amount;
    public InviteePayment withAmount(Float amount) {
        this.amount = amount;
        return this;
    }
    
    /**
     * The currency format that the payment is in.
     */
    @JsonProperty("currency")
    public InviteePaymentCurrencyEnum currency;
    public InviteePayment withCurrency(InviteePaymentCurrencyEnum currency) {
        this.currency = currency;
        return this;
    }
    
    /**
     * Unique identifier for the payment
     */
    @JsonProperty("external_id")
    public String externalId;
    public InviteePayment withExternalId(String externalId) {
        this.externalId = externalId;
        return this;
    }
    
    /**
     * Payment provider
     */
    @JsonProperty("provider")
    public InviteePaymentProviderEnum provider;
    public InviteePayment withProvider(InviteePaymentProviderEnum provider) {
        this.provider = provider;
        return this;
    }
    
    /**
     * Indicates whether the payment was successfully processed
     */
    @JsonProperty("successful")
    public Boolean successful;
    public InviteePayment withSuccessful(Boolean successful) {
        this.successful = successful;
        return this;
    }
    
    /**
     * Terms of the payment
     */
    @JsonProperty("terms")
    public String terms;
    public InviteePayment withTerms(String terms) {
        this.terms = terms;
        return this;
    }
    
}
