/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * InviteePaymentCurrencyEnum - The currency format that the payment is in.
 */
public enum InviteePaymentCurrencyEnum {
    AUD("AUD"),
    CAD("CAD"),
    EUR("EUR"),
    GBP("GBP"),
    USD("USD");

    @JsonValue
    public final String value;

    private InviteePaymentCurrencyEnum(String value) {
        this.value = value;
    }
}
