/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * LegacyCalendarEvent - Information about the calendar event from the calendar provider.
 */
public class LegacyCalendarEvent {
    /**
     * the id provided from the calendar provider for this calendar event.
     */
    @JsonProperty("external_id")
    public String externalId;
    public LegacyCalendarEvent withExternalId(String externalId) {
        this.externalId = externalId;
        return this;
    }
    
    /**
     * Indicates the calendar provider the event belongs to.
     */
    @JsonProperty("kind")
    public LegacyCalendarEventKindEnum kind;
    public LegacyCalendarEvent withKind(LegacyCalendarEventKindEnum kind) {
        this.kind = kind;
        return this;
    }
    
}
