/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * LegacyCalendarEventKindEnum - Indicates the calendar provider the event belongs to.
 */
public enum LegacyCalendarEventKindEnum {
    EXCHANGE("exchange"),
    GOOGLE("google"),
    ICLOUD("icloud"),
    OUTLOOK("outlook"),
    OUTLOOK_DESKTOP("outlook_desktop");

    @JsonValue
    public final String value;

    private LegacyCalendarEventKindEnum(String value) {
        this.value = value;
    }
}
