/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * MicrosoftTeamsConference - Meeting will take place in a Microsoft Teams conference
 */
public class MicrosoftTeamsConference {
    /**
     * The conference metadata supplied by Microsoft Teams
     */
    @JsonProperty("data")public MicrosoftTeamsConferenceData data;
    public MicrosoftTeamsConference withData(MicrosoftTeamsConferenceData data) {
        this.data = data;
        return this;
    }
    
    /**
     * Microsoft Teams meeting url
     */
    @JsonProperty("join_url")public String joinUrl;
    public MicrosoftTeamsConference withJoinUrl(String joinUrl) {
        this.joinUrl = joinUrl;
        return this;
    }
    
    /**
     * Indicates the current status of the Microsoft Teams conference
     */
    @JsonProperty("status")public MicrosoftTeamsConferenceStatusEnum status;
    public MicrosoftTeamsConference withStatus(MicrosoftTeamsConferenceStatusEnum status) {
        this.status = status;
        return this;
    }
    
    /**
     * The event location is a Zoom conference
     */
    @JsonProperty("type")public MicrosoftTeamsConferenceTypeEnum type;
    public MicrosoftTeamsConference withType(MicrosoftTeamsConferenceTypeEnum type) {
        this.type = type;
        return this;
    }
    
}
