/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * OrganizationMembershipRoleEnum - The user's role in the organization
 */
public enum OrganizationMembershipRoleEnum {
    USER("user"),
    ADMIN("admin"),
    OWNER("owner");

    @JsonValue
    public final String value;

    private OrganizationMembershipRoleEnum(String value) {
        this.value = value;
    }
}
