/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * OrganizationInvitationStatusEnum - The status of the invitation ("pending", "accepted", or "declined")
 */
public enum OrganizationInvitationStatusEnum {
    PENDING("pending"),
    ACCEPTED("accepted"),
    DECLINED("declined");

    @JsonValue
    public final String value;

    private OrganizationInvitationStatusEnum(String value) {
        this.value = value;
    }
}
