/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * OutboundCall - Meeting publisher will call the Invitee
 */
public class OutboundCall {
    /**
     * The phone number the event host (publisher) will use to call the invitee
     */
    @JsonProperty("location")
    public String location;
    public OutboundCall withLocation(String location) {
        this.location = location;
        return this;
    }
    
    /**
     * Indicates that the event host (publisher) will call the invitee
     */
    @JsonProperty("type")
    public OutboundCallTypeEnum type;
    public OutboundCall withType(OutboundCallTypeEnum type) {
        this.type = type;
        return this;
    }
    
}
