/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * OutboundCallTypeEnum - Indicates that the event host (publisher) will call the invitee
 */
public enum OutboundCallTypeEnum {
    OUTBOUND_CALL("outbound_call");

    @JsonValue
    public final String value;

    private OutboundCallTypeEnum(String value) {
        this.value = value;
    }
}
