/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Profile - The publicly visible profile of a User or a Team that's associated with the Event Type (note: some Event Types don't have profiles)
 */
public class Profile {
    /**
     * Human-readable name for the profile of the user that's associated with the event type
     */
    @JsonProperty("name")
    public String name;
    public Profile withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * The unique reference to the user associated with the profile
     */
    @JsonProperty("owner")
    public String owner;
    public Profile withOwner(String owner) {
        this.owner = owner;
        return this;
    }
    
    /**
     * Indicates if the profile belongs to a "user" (individual) or "team"
     */
    @JsonProperty("type")
    public ProfileTypeEnum type;
    public Profile withType(ProfileTypeEnum type) {
        this.type = type;
        return this;
    }
    
}
