/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * QuestionTypeEnum - Question type: name, text input, email, phone, textarea input, dropdown list or radio button list.
 */
public enum QuestionTypeEnum {
    NAME("name"),
    TEXT("text"),
    EMAIL("email"),
    PHONE("phone"),
    TEXTAREA("textarea"),
    SELECT("select"),
    RADIOS("radios");

    @JsonValue
    public final String value;

    private QuestionTypeEnum(String value) {
        this.value = value;
    }
}
