/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Question - Routing form questions.
 */
public class Question {
    /**
     * The respondent\u2019s option(s) for "select" or "radios" types of questions.
     */
    @JsonProperty("answer_choices")
    public String[] answerChoices;
    public Question withAnswerChoices(String[] answerChoices) {
        this.answerChoices = answerChoices;
        return this;
    }
    
    /**
     * Question name (in human-readable format).
     */
    @JsonProperty("name")
    public String name;
    public Question withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * true if an answer to the question is required for respondents to submit the routing form; false if not required.
     * 
     */
    @JsonProperty("required")
    public Boolean required;
    public Question withRequired(Boolean required) {
        this.required = required;
        return this;
    }
    
    /**
     * Question type: name, text input, email, phone, textarea input, dropdown list or radio button list.
     */
    @JsonProperty("type")
    public QuestionTypeEnum type;
    public Question withType(QuestionTypeEnum type) {
        this.type = type;
        return this;
    }
    
    /**
     * Unique identifier for the routing form question.
     */
    @JsonProperty("uuid")
    public String uuid;
    public Question withUuid(String uuid) {
        this.uuid = uuid;
        return this;
    }
    
}
