/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import calendly.calendly.utils.DateTimeDeserializer;
import calendly.calendly.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

/**
 * RoutingFormSubmission - Information about a Routing Form Submission.
 */
public class RoutingFormSubmission {
    /**
     * The moment the routing form was submitted.
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created_at")public OffsetDateTime createdAt;
    public RoutingFormSubmission withCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }
    
    /**
     * All Routing Form Submission questions with answers.
     */
    @JsonProperty("questions_and_answers")public SubmissionQuestionAndAnswer[] questionsAndAnswers;
    public RoutingFormSubmission withQuestionsAndAnswers(SubmissionQuestionAndAnswer[] questionsAndAnswers) {
        this.questionsAndAnswers = questionsAndAnswers;
        return this;
    }
    
    /**
     * The polymorphic base type for a Routing Form Submission result.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("result")public Object result;
    public RoutingFormSubmission withResult(Object result) {
        this.result = result;
        return this;
    }
    
    /**
     * The URI of the routing form that's associated with the submission.
     */
    @JsonProperty("routing_form")public String routingForm;
    public RoutingFormSubmission withRoutingForm(String routingForm) {
        this.routingForm = routingForm;
        return this;
    }
    
    /**
     * The reference to the Invitee resource when routing form submission results in a scheduled meeting.
     */
    @JsonProperty("submitter")public String submitter;
    public RoutingFormSubmission withSubmitter(String submitter) {
        this.submitter = submitter;
        return this;
    }
    
    /**
     * Type of the respondent resource that submitted the form and scheduled a meeting.
     */
    @JsonProperty("submitter_type")public RoutingFormSubmissionSubmitterTypeEnum submitterType;
    public RoutingFormSubmission withSubmitterType(RoutingFormSubmissionSubmitterTypeEnum submitterType) {
        this.submitterType = submitterType;
        return this;
    }
    
    /**
     * The UTM and Salesforce tracking parameters associated with a Routing Form Submission.
     */
    @JsonProperty("tracking")public SubmissionTracking tracking;
    public RoutingFormSubmission withTracking(SubmissionTracking tracking) {
        this.tracking = tracking;
        return this;
    }
    
    /**
     * The moment when the routing form submission was last updated.
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated_at")public OffsetDateTime updatedAt;
    public RoutingFormSubmission withUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }
    
    /**
     * Canonical reference (unique identifier) for the routing form submission.
     */
    @JsonProperty("uri")public String uri;
    public RoutingFormSubmission withUri(String uri) {
        this.uri = uri;
        return this;
    }
    
}
