/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * RoutingFormStatusEnum - Indicates if the form is in "draft" or "published" status.
 */
public enum RoutingFormStatusEnum {
    DRAFT("draft"),
    PUBLISHED("published");

    @JsonValue
    public final String value;

    private RoutingFormStatusEnum(String value) {
        this.value = value;
    }
}
