/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ShareSchedulingLinks {
    /**
     * Scheduling link url
     */
    @JsonProperty("booking_url")
    public String bookingUrl;
    public ShareSchedulingLinks withBookingUrl(String bookingUrl) {
        this.bookingUrl = bookingUrl;
        return this;
    }
    
    /**
     * A link to the resource that owns this Scheduling Link (currently, this is always an Event Type)
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("owner")
    public String owner;
    public ShareSchedulingLinks withOwner(String owner) {
        this.owner = owner;
        return this;
    }
    
    /**
     * Resource type (currently, this is always EventType)
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("owner_type")
    public ShareSchedulingLinksOwnerTypeEnum ownerType;
    public ShareSchedulingLinks withOwnerType(ShareSchedulingLinksOwnerTypeEnum ownerType) {
        this.ownerType = ownerType;
        return this;
    }
    
}
