/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ShareSchedulingLinksOwnerTypeEnum - Resource type (currently, this is always EventType)
 */
public enum ShareSchedulingLinksOwnerTypeEnum {
    EVENT_TYPE("EventType");

    @JsonValue
    public final String value;

    private ShareSchedulingLinksOwnerTypeEnum(String value) {
        this.value = value;
    }
}
