/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SubmissionExternalUrlResult - Information about the external URL Routing Form Submission result.
 */
public class SubmissionExternalUrlResult {
    /**
     * Indicates that the routing form submission resulted in a redirect to an external URL.
     */
    @JsonProperty("type")
    public SubmissionExternalUrlResultTypeEnum type;
    public SubmissionExternalUrlResult withType(SubmissionExternalUrlResultTypeEnum type) {
        this.type = type;
        return this;
    }
    
    /**
     * The external URL the respondent were redirected to.
     */
    @JsonProperty("value")
    public String value;
    public SubmissionExternalUrlResult withValue(String value) {
        this.value = value;
        return this;
    }
    
}
