/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SubmissionExternalUrlResultTypeEnum - Indicates that the routing form submission resulted in a redirect to an external URL.
 */
public enum SubmissionExternalUrlResultTypeEnum {
    EXTERNAL_URL("external_url");

    @JsonValue
    public final String value;

    private SubmissionExternalUrlResultTypeEnum(String value) {
        this.value = value;
    }
}
