/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SubmissionEventTypeResultTypeEnum - Indicates that the routing form submission resulted in a redirect to an event type booking page.
 */
public enum SubmissionEventTypeResultTypeEnum {
    EVENT_TYPE("event_type");

    @JsonValue
    public final String value;

    private SubmissionEventTypeResultTypeEnum(String value) {
        this.value = value;
    }
}
