/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SubmissionCustomMessageResultTypeEnum - Indicates if the routing form submission resulted in a custom "thank you" message.
 */
public enum SubmissionCustomMessageResultTypeEnum {
    CUSTOM_MESSAGE("custom_message");

    @JsonValue
    public final String value;

    private SubmissionCustomMessageResultTypeEnum(String value) {
        this.value = value;
    }
}
