/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SubmissionCustomMessageResultValue - Contains an object with custom message headline and body.
 */
public class SubmissionCustomMessageResultValue {
    /**
     * Body text displayed when answers don't match any routes.
     */
    @JsonProperty("body")
    public String body;
    public SubmissionCustomMessageResultValue withBody(String body) {
        this.body = body;
        return this;
    }
    
    /**
     * Headline displayed when answers don't match any routes.
     */
    @JsonProperty("headline")
    public String headline;
    public SubmissionCustomMessageResultValue withHeadline(String headline) {
        this.headline = headline;
        return this;
    }
    
}
