/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UserBusyTimeEvent {
    /**
     * The uri associated with the calendly scheduled event
     */
    @JsonProperty("uri")
    public String uri;
    public UserBusyTimeEvent withUri(String uri) {
        this.uri = uri;
        return this;
    }
    
}
