/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * WebExConferenceTypeEnum - The event location is a WebEx conference
 */
public enum WebExConferenceTypeEnum {
    WEBEX_CONFERENCE("webex_conference");

    @JsonValue
    public final String value;

    private WebExConferenceTypeEnum(String value) {
        this.value = value;
    }
}
