/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import calendly.calendly.utils.DateTimeDeserializer;
import calendly.calendly.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

/**
 * WebhookSubscription - Webhook Subscription Object
 */
public class WebhookSubscription {
    /**
     * The callback URL to use when the event is triggered
     */
    @JsonProperty("callback_url")
    public String callbackUrl;
    public WebhookSubscription withCallbackUrl(String callbackUrl) {
        this.callbackUrl = callbackUrl;
        return this;
    }
    
    /**
     * The moment when the webhook subscription was created (e.g. "2020-01-02T03:04:05.678123Z")
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created_at")
    public OffsetDateTime createdAt;
    public WebhookSubscription withCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }
    
    /**
     * The URI of the user who created the webhook subscription
     */
    @JsonProperty("creator")
    public String creator;
    public WebhookSubscription withCreator(String creator) {
        this.creator = creator;
        return this;
    }
    
    /**
     * A list of events to which the webhook is subscribed
     */
    @JsonProperty("events")
    public WebhookSubscriptionEventsEnum[] events;
    public WebhookSubscription withEvents(WebhookSubscriptionEventsEnum[] events) {
        this.events = events;
        return this;
    }
    
    /**
     * The URI of the organization that's associated with the webhook subscription
     */
    @JsonProperty("organization")
    public String organization;
    public WebhookSubscription withOrganization(String organization) {
        this.organization = organization;
        return this;
    }
    
    /**
     * The date and time the webhook subscription is retried
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("retry_started_at")
    public OffsetDateTime retryStartedAt;
    public WebhookSubscription withRetryStartedAt(OffsetDateTime retryStartedAt) {
        this.retryStartedAt = retryStartedAt;
        return this;
    }
    
    /**
     * The scope of the webhook subscription
     */
    @JsonProperty("scope")
    public WebhookSubscriptionScopeEnum scope;
    public WebhookSubscription withScope(WebhookSubscriptionScopeEnum scope) {
        this.scope = scope;
        return this;
    }
    
    /**
     * Indicates if the webhook subscription is "active" or "disabled"
     */
    @JsonProperty("state")
    public WebhookSubscriptionStateEnum state;
    public WebhookSubscription withState(WebhookSubscriptionStateEnum state) {
        this.state = state;
        return this;
    }
    
    /**
     * The moment when the webhook subscription was last updated (e.g. "2020-01-02T03:04:05.678123Z")
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated_at")
    public OffsetDateTime updatedAt;
    public WebhookSubscription withUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }
    
    /**
     * Canonical reference (unique identifier) for the webhook
     */
    @JsonProperty("uri")
    public String uri;
    public WebhookSubscription withUri(String uri) {
        this.uri = uri;
        return this;
    }
    
    /**
     * The URI of the user that's associated with the webhook subscription
     */
    @JsonProperty("user")
    public String user;
    public WebhookSubscription withUser(String user) {
        this.user = user;
        return this;
    }
    
}
