/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * WebhookSubscriptionScopeEnum - The scope of the webhook subscription
 */
public enum WebhookSubscriptionScopeEnum {
    USER("user"),
    ORGANIZATION("organization");

    @JsonValue
    public final String value;

    private WebhookSubscriptionScopeEnum(String value) {
        this.value = value;
    }
}
