/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * WebhookSubscriptionStateEnum - Indicates if the webhook subscription is "active" or "disabled"
 */
public enum WebhookSubscriptionStateEnum {
    ACTIVE("active"),
    DISABLED("disabled");

    @JsonValue
    public final String value;

    private WebhookSubscriptionStateEnum(String value) {
        this.value = value;
    }
}
