/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ZoomConferenceTypeEnum - The event location is a Zoom conference
 */
public enum ZoomConferenceTypeEnum {
    ZOOM_CONFERENCE("zoom_conference");

    @JsonValue
    public final String value;

    private ZoomConferenceTypeEnum(String value) {
        this.value = value;
    }
}
