/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ZoomConference - Meeting will take place in a Zoom conference
 */
public class ZoomConference {
    /**
     * The conference metadata supplied by Zoom
     */
    @JsonProperty("data")public ZoomConferenceData data;
    public ZoomConference withData(ZoomConferenceData data) {
        this.data = data;
        return this;
    }
    
    /**
     * Zoom meeting url
     */
    @JsonProperty("join_url")public String joinUrl;
    public ZoomConference withJoinUrl(String joinUrl) {
        this.joinUrl = joinUrl;
        return this;
    }
    
    /**
     * Indicates the current status of the Zoom conference
     */
    @JsonProperty("status")public ZoomConferenceStatusEnum status;
    public ZoomConference withStatus(ZoomConferenceStatusEnum status) {
        this.status = status;
        return this;
    }
    
    /**
     * The event location is a Zoom conference
     */
    @JsonProperty("type")public ZoomConferenceTypeEnum type;
    public ZoomConference withType(ZoomConferenceTypeEnum type) {
        this.type = type;
        return this;
    }
    
}
