/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;



public class DeleteUsersUserUuidWebhooksWebhookUuidRequest {
    public DeleteUsersUserUuidWebhooksWebhookUuidPathParams pathParams;
    public DeleteUsersUserUuidWebhooksWebhookUuidRequest withPathParams(DeleteUsersUserUuidWebhooksWebhookUuidPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
}
