/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;



public class DeleteInviteeNoShowRequest {
    public DeleteInviteeNoShowPathParams pathParams;
    public DeleteInviteeNoShowRequest withPathParams(DeleteInviteeNoShowPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
}
