/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import calendly.calendly.utils.SpeakeasyMetadata;

public class DeleteInviteeNoShowRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=uuid")
    public String uuid;
    public DeleteInviteeNoShowRequest withUuid(String uuid) {
        this.uuid = uuid;
        return this;
    }
    
}
