/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;



public class GetEventTypeAvailableTimesRequest {
    public GetEventTypeAvailableTimesQueryParams queryParams;
    public GetEventTypeAvailableTimesRequest withQueryParams(GetEventTypeAvailableTimesQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
}
