/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;



public class GetEventTypesRequest {
    public GetEventTypesQueryParams queryParams;
    public GetEventTypesRequest withQueryParams(GetEventTypesQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
}
