/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import calendly.calendly.utils.SpeakeasyMetadata;

public class GetEventTypeAvailableTimesQueryParams {
    /**
     * End time of the requested availability range.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=end_time")public String endTime;
    public GetEventTypeAvailableTimesQueryParams withEndTime(String endTime) {
        this.endTime = endTime;
        return this;
    }
    
    /**
     * The uri associated with the event type
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=event_type")public String eventType;
    public GetEventTypeAvailableTimesQueryParams withEventType(String eventType) {
        this.eventType = eventType;
        return this;
    }
    
    /**
     * Start time of the requested availability range.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=start_time")public String startTime;
    public GetEventTypeAvailableTimesQueryParams withStartTime(String startTime) {
        this.startTime = startTime;
        return this;
    }
    
}
