/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;



public class GetInviteeNoShowRequest {
    public GetInviteeNoShowPathParams pathParams;
    public GetInviteeNoShowRequest withPathParams(GetInviteeNoShowPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
}
