/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GetInviteesStatusEnum - Indicates if the invitee "canceled" or still "active"
 */
public enum GetInviteesStatusEnum {
    ACTIVE("active"),
    CANCELED("canceled");

    @JsonValue
    public final String value;

    private GetInviteesStatusEnum(String value) {
        this.value = value;
    }
}
