/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;



public class GetOrganizationMembershipsRequest {
    public GetOrganizationMembershipsQueryParams queryParams;
    public GetOrganizationMembershipsRequest withQueryParams(GetOrganizationMembershipsQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
}
