/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetOrganizationsOrgUuidInvitationsUuid200ApplicationJSON - OK
 */
public class GetOrganizationsOrgUuidInvitationsUuid200ApplicationJSON {
    /**
     * Organization Invitation object
     */
    @JsonProperty("resource")public calendly.calendly.models.shared.OrganizationInvitation resource;
    public GetOrganizationsOrgUuidInvitationsUuid200ApplicationJSON withResource(calendly.calendly.models.shared.OrganizationInvitation resource) {
        this.resource = resource;
        return this;
    }
    
}
