/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetOrganizationsUuidMemberships200ApplicationJSON - OK
 */
public class GetOrganizationsUuidMemberships200ApplicationJSON {
    @JsonProperty("resource")
    public calendly.calendly.models.shared.OrganizationMembership resource;
    public GetOrganizationsUuidMemberships200ApplicationJSON withResource(calendly.calendly.models.shared.OrganizationMembership resource) {
        this.resource = resource;
        return this;
    }
    
}
