/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;



public class GetOrganizationsUuidMembershipsRequest {
    public GetOrganizationsUuidMembershipsPathParams pathParams;
    public GetOrganizationsUuidMembershipsRequest withPathParams(GetOrganizationsUuidMembershipsPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
}
