/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import calendly.calendly.utils.SpeakeasyMetadata;

public class GetOrganizationsOrgUuidInvitationsUuidPathParams {
    /**
     * The organization’s unique identifier
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_uuid")public String orgUuid;
    public GetOrganizationsOrgUuidInvitationsUuidPathParams withOrgUuid(String orgUuid) {
        this.orgUuid = orgUuid;
        return this;
    }
    
    /**
     * The organization invitation's unique identifier
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=uuid")public String uuid;
    public GetOrganizationsOrgUuidInvitationsUuidPathParams withUuid(String uuid) {
        this.uuid = uuid;
        return this;
    }
    
}
