/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import calendly.calendly.utils.SpeakeasyMetadata;

public class GetOrganizationsUuidInvitationsQueryParams {
    /**
     * The number of rows to return
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=count")public Double count;
    public GetOrganizationsUuidInvitationsQueryParams withCount(Double count) {
        this.count = count;
        return this;
    }
    
    /**
     * Indicates if the results should be filtered by email address
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=email")public String email;
    public GetOrganizationsUuidInvitationsQueryParams withEmail(String email) {
        this.email = email;
        return this;
    }
    
    /**
     * The token to pass to get the next or previous portion of the collection
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page_token")public String pageToken;
    public GetOrganizationsUuidInvitationsQueryParams withPageToken(String pageToken) {
        this.pageToken = pageToken;
        return this;
    }
    
    /**
     * Order results by the field name and direction specified (ascending or descending). Returns multiple sets of results in a comma-separated list.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=sort")public String sort;
    public GetOrganizationsUuidInvitationsQueryParams withSort(String sort) {
        this.sort = sort;
        return this;
    }
    
    /**
     * Indicates if the results should be filtered by status  ("pending", "accepted", or "declined")
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=status")public GetOrganizationsUuidInvitationsStatusEnum status;
    public GetOrganizationsUuidInvitationsQueryParams withStatus(GetOrganizationsUuidInvitationsStatusEnum status) {
        this.status = status;
        return this;
    }
    
}
