/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import calendly.calendly.utils.SpeakeasyMetadata;

public class GetOrganizationsUuidMembershipsPathParams {
    /**
     * The organization membership's unique identifier
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=uuid")public String uuid;
    public GetOrganizationsUuidMembershipsPathParams withUuid(String uuid) {
        this.uuid = uuid;
        return this;
    }
    
}
