/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GetOrganizationsUuidInvitationsStatusEnum - Indicates if the results should be filtered by status  ("pending", "accepted", or "declined")
 */
public enum GetOrganizationsUuidInvitationsStatusEnum {
    PENDING("pending"),
    ACCEPTED("accepted"),
    DECLINED("declined");

    @JsonValue
    public final String value;

    private GetOrganizationsUuidInvitationsStatusEnum(String value) {
        this.value = value;
    }
}
