/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetRoutingFormSubmissionsUuid200ApplicationJSON - OK
 */
public class GetRoutingFormSubmissionsUuid200ApplicationJSON {
    /**
     * Information about a Routing Form Submission.
     */
    @JsonProperty("resource")
    public calendly.calendly.models.shared.RoutingFormSubmission resource;
    public GetRoutingFormSubmissionsUuid200ApplicationJSON withResource(calendly.calendly.models.shared.RoutingFormSubmission resource) {
        this.resource = resource;
        return this;
    }
    
}
