/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;



public class GetRoutingFormsRequest {
    public GetRoutingFormsQueryParams queryParams;
    public GetRoutingFormsRequest withQueryParams(GetRoutingFormsQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
}
