/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;



public class GetRoutingFormSubmissionsRequest {
    public GetRoutingFormSubmissionsQueryParams queryParams;
    public GetRoutingFormSubmissionsRequest withQueryParams(GetRoutingFormSubmissionsQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
}
