/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;



public class GetScheduledEventsRequest {
    public GetScheduledEventsQueryParams queryParams;
    public GetScheduledEventsRequest withQueryParams(GetScheduledEventsQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
}
