/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetScheduledEventsEventUuidInviteesInviteeUuid200ApplicationJSON - OK
 */
public class GetScheduledEventsEventUuidInviteesInviteeUuid200ApplicationJSON {
    /**
     * An individual who has been invited to meet with a Calendly member
     */
    @JsonProperty("resource")public calendly.calendly.models.shared.Invitee resource;
    public GetScheduledEventsEventUuidInviteesInviteeUuid200ApplicationJSON withResource(calendly.calendly.models.shared.Invitee resource) {
        this.resource = resource;
        return this;
    }
    
}
