/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;



public class GetScheduledEventsUuidRequest {
    public GetScheduledEventsUuidPathParams pathParams;
    public GetScheduledEventsUuidRequest withPathParams(GetScheduledEventsUuidPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
}
