/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetScheduledEventsUuid200ApplicationJSON - OK
 */
public class GetScheduledEventsUuid200ApplicationJSON {
    /**
     * Information about a scheduled meeting
     */
    @JsonProperty("resource")public calendly.calendly.models.shared.Event resource;
    public GetScheduledEventsUuid200ApplicationJSON withResource(calendly.calendly.models.shared.Event resource) {
        this.resource = resource;
        return this;
    }
    
}
