/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GetScheduledEventsStatusEnum - Whether the scheduled event is `active` or `canceled`
 */
public enum GetScheduledEventsStatusEnum {
    ACTIVE("active"),
    CANCELED("canceled");

    @JsonValue
    public final String value;

    private GetScheduledEventsStatusEnum(String value) {
        this.value = value;
    }
}
