/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;



public class GetScheduledEventsEventUuidInviteesInviteeUuidRequest {
    public GetScheduledEventsEventUuidInviteesInviteeUuidPathParams pathParams;
    public GetScheduledEventsEventUuidInviteesInviteeUuidRequest withPathParams(GetScheduledEventsEventUuidInviteesInviteeUuidPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
}
