/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetUserAvailabilitySchedulesUuid200ApplicationJSON - OK
 */
public class GetUserAvailabilitySchedulesUuid200ApplicationJSON {
    /**
     * The availability schedule set by the user.
     */
    @JsonProperty("resource")public calendly.calendly.models.shared.AvailabilitySchedule resource;
    public GetUserAvailabilitySchedulesUuid200ApplicationJSON withResource(calendly.calendly.models.shared.AvailabilitySchedule resource) {
        this.resource = resource;
        return this;
    }
    
}
