/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import calendly.calendly.utils.SpeakeasyMetadata;

public class GetUserAvailabilitySchedulesQueryParams {
    /**
     * A URI reference to a user
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=user")public String user;
    public GetUserAvailabilitySchedulesQueryParams withUser(String user) {
        this.user = user;
        return this;
    }
    
}
