/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;



public class GetUserRequest {
    public GetUserPathParams pathParams;
    public GetUserRequest withPathParams(GetUserPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
}
