/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;



public class GetUserAvailabilitySchedulesRequest {
    public GetUserAvailabilitySchedulesQueryParams queryParams;
    public GetUserAvailabilitySchedulesRequest withQueryParams(GetUserAvailabilitySchedulesQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
}
