/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;



public class GetUserAvailabilitySchedulesUuidRequest {
    public GetUserAvailabilitySchedulesUuidPathParams pathParams;
    public GetUserAvailabilitySchedulesUuidRequest withPathParams(GetUserAvailabilitySchedulesUuidPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
}
