/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetUsersUserUuidWebhooksWebhookUuid200ApplicationJSON - OK
 */
public class GetUsersUserUuidWebhooksWebhookUuid200ApplicationJSON {
    /**
     * Webhook Subscription Object
     */
    @JsonProperty("resource")public calendly.calendly.models.shared.WebhookSubscription resource;
    public GetUsersUserUuidWebhooksWebhookUuid200ApplicationJSON withResource(calendly.calendly.models.shared.WebhookSubscription resource) {
        this.resource = resource;
        return this;
    }
    
}
