/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;



public class GetWebhooksRequest {
    public GetWebhooksQueryParams queryParams;
    public GetWebhooksRequest withQueryParams(GetWebhooksQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
}
