/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import calendly.calendly.utils.SpeakeasyMetadata;

public class GetWebhooksRequest {
    /**
     * The number of rows to return
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=count")
    public Double count;
    public GetWebhooksRequest withCount(Double count) {
        this.count = count;
        return this;
    }
    
    /**
     * Indicates if the results should be filtered by organization
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=organization")
    public String organization;
    public GetWebhooksRequest withOrganization(String organization) {
        this.organization = organization;
        return this;
    }
    
    /**
     * The token to pass to get the next or previous portion of the collection
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page_token")
    public String pageToken;
    public GetWebhooksRequest withPageToken(String pageToken) {
        this.pageToken = pageToken;
        return this;
    }
    
    /**
     * Filter the list by organization or user
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=scope")
    public GetWebhooksScopeEnum scope;
    public GetWebhooksRequest withScope(GetWebhooksScopeEnum scope) {
        this.scope = scope;
        return this;
    }
    
    /**
     * Order results by the specified field and direction. Accepts comma-separated list of {field}:{direction} values.
     * Supported fields are: created_at.
     * Sort direction is specified as: asc, desc.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=sort")
    public String sort;
    public GetWebhooksRequest withSort(String sort) {
        this.sort = sort;
        return this;
    }
    
    /**
     * Indicates if the results should be filtered by user. This parameter is only required if the `scope` parameter is set to `user`.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=user")
    public String user;
    public GetWebhooksRequest withUser(String user) {
        this.user = user;
        return this;
    }
    
}
