/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import java.net.http.HttpResponse;

public class ListOrganizationMembershipsResponse {
    
    public String contentType;
    public ListOrganizationMembershipsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Request is not valid
     */
    
    public ListOrganizationMembershipsErrorResponse errorResponse;
    public ListOrganizationMembershipsResponse withErrorResponse(ListOrganizationMembershipsErrorResponse errorResponse) {
        this.errorResponse = errorResponse;
        return this;
    }
    
    /**
     * Caller not authorized to perform this action
     */
    
    public calendly.calendly.models.shared.ErrorResponse errorResponse1;
    public ListOrganizationMembershipsResponse withErrorResponse1(calendly.calendly.models.shared.ErrorResponse errorResponse1) {
        this.errorResponse1 = errorResponse1;
        return this;
    }
    
    
    public Integer statusCode;
    public ListOrganizationMembershipsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public ListOrganizationMembershipsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public ListOrganizationMemberships200ApplicationJSON listOrganizationMemberships200ApplicationJSONObject;
    public ListOrganizationMembershipsResponse withListOrganizationMemberships200ApplicationJSONObject(ListOrganizationMemberships200ApplicationJSON listOrganizationMemberships200ApplicationJSONObject) {
        this.listOrganizationMemberships200ApplicationJSONObject = listOrganizationMemberships200ApplicationJSONObject;
        return this;
    }
    
}
