/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ListWebhooks403ApplicationJSONMessageEnum {
    YOU_DO_NOT_HAVE_PERMISSION("You do not have permission"),
    YOU_DO_NOT_HAVE_PERMISSION_TO_ACCESS_THIS_RESOURCE("You do not have permission to access this resource."),
    UNAUTHORIZED("Unauthorized");

    @JsonValue
    public final String value;

    private ListWebhooks403ApplicationJSONMessageEnum(String value) {
        this.value = value;
    }
}
