/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import java.net.http.HttpResponse;

public class ListEventTypesResponse {
    
    public String contentType;
    public ListEventTypesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Request is not valid
     */
    
    public ListEventTypesErrorResponse errorResponse;
    public ListEventTypesResponse withErrorResponse(ListEventTypesErrorResponse errorResponse) {
        this.errorResponse = errorResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public ListEventTypesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public ListEventTypesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public ListEventTypes200ApplicationJSON listEventTypes200ApplicationJSONObject;
    public ListEventTypesResponse withListEventTypes200ApplicationJSONObject(ListEventTypes200ApplicationJSON listEventTypes200ApplicationJSONObject) {
        this.listEventTypes200ApplicationJSONObject = listEventTypes200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Permission Denied
     */
    
    public ListEventTypes403ApplicationJSON listEventTypes403ApplicationJSONObject;
    public ListEventTypesResponse withListEventTypes403ApplicationJSONObject(ListEventTypes403ApplicationJSON listEventTypes403ApplicationJSONObject) {
        this.listEventTypes403ApplicationJSONObject = listEventTypes403ApplicationJSONObject;
        return this;
    }
    
}
