/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListScheduledEvents200ApplicationJSON - Service response
 */
public class ListScheduledEvents200ApplicationJSON {
    /**
     * The set of scheduled events matching the criteria
     */
    @JsonProperty("collection")
    public calendly.calendly.models.shared.Event[] collection;
    public ListScheduledEvents200ApplicationJSON withCollection(calendly.calendly.models.shared.Event[] collection) {
        this.collection = collection;
        return this;
    }
    
    @JsonProperty("pagination")
    public calendly.calendly.models.shared.Pagination pagination;
    public ListScheduledEvents200ApplicationJSON withPagination(calendly.calendly.models.shared.Pagination pagination) {
        this.pagination = pagination;
        return this;
    }
    
}
