/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListActivityLog403ApplicationJSON - Permission Denied
 */
public class ListActivityLog403ApplicationJSON {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("message")
    public ListActivityLog403ApplicationJSONMessageEnum message;
    public ListActivityLog403ApplicationJSON withMessage(ListActivityLog403ApplicationJSONMessageEnum message) {
        this.message = message;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("title")
    public ListActivityLog403ApplicationJSONTitleEnum title;
    public ListActivityLog403ApplicationJSON withTitle(ListActivityLog403ApplicationJSONTitleEnum title) {
        this.title = title;
        return this;
    }
    
}
