/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import java.net.http.HttpResponse;

public class ListScheduledEventsResponse {
    
    public String contentType;
    public ListScheduledEventsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Request is not valid
     */
    
    public ListScheduledEventsErrorResponse errorResponse;
    public ListScheduledEventsResponse withErrorResponse(ListScheduledEventsErrorResponse errorResponse) {
        this.errorResponse = errorResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public ListScheduledEventsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public ListScheduledEventsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public ListScheduledEvents200ApplicationJSON listScheduledEvents200ApplicationJSONObject;
    public ListScheduledEventsResponse withListScheduledEvents200ApplicationJSONObject(ListScheduledEvents200ApplicationJSON listScheduledEvents200ApplicationJSONObject) {
        this.listScheduledEvents200ApplicationJSONObject = listScheduledEvents200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Permission Denied
     */
    
    public ListScheduledEvents403ApplicationJSON listScheduledEvents403ApplicationJSONObject;
    public ListScheduledEventsResponse withListScheduledEvents403ApplicationJSONObject(ListScheduledEvents403ApplicationJSON listScheduledEvents403ApplicationJSONObject) {
        this.listScheduledEvents403ApplicationJSONObject = listScheduledEvents403ApplicationJSONObject;
        return this;
    }
    
}
