/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListRoutingFormsErrorResponse - Error Object
 */
public class ListRoutingFormsErrorResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("details")
    public ListRoutingFormsErrorResponseDetails[] details;
    public ListRoutingFormsErrorResponse withDetails(ListRoutingFormsErrorResponseDetails[] details) {
        this.details = details;
        return this;
    }
    
    @JsonProperty("message")
    public String message;
    public ListRoutingFormsErrorResponse withMessage(String message) {
        this.message = message;
        return this;
    }
    
    @JsonProperty("title")
    public String title;
    public ListRoutingFormsErrorResponse withTitle(String title) {
        this.title = title;
        return this;
    }
    
}
