/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import java.net.http.HttpResponse;

public class ListWebhooksResponse {
    
    public String contentType;
    public ListWebhooksResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Request is not valid
     */
    
    public ListWebhooksErrorResponse errorResponse;
    public ListWebhooksResponse withErrorResponse(ListWebhooksErrorResponse errorResponse) {
        this.errorResponse = errorResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public ListWebhooksResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public ListWebhooksResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public ListWebhooks200ApplicationJSON listWebhooks200ApplicationJSONObject;
    public ListWebhooksResponse withListWebhooks200ApplicationJSONObject(ListWebhooks200ApplicationJSON listWebhooks200ApplicationJSONObject) {
        this.listWebhooks200ApplicationJSONObject = listWebhooks200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Permission Denied
     */
    
    public ListWebhooks403ApplicationJSON listWebhooks403ApplicationJSONObject;
    public ListWebhooksResponse withListWebhooks403ApplicationJSONObject(ListWebhooks403ApplicationJSON listWebhooks403ApplicationJSONObject) {
        this.listWebhooks403ApplicationJSONObject = listWebhooks403ApplicationJSONObject;
        return this;
    }
    
}
