/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import calendly.calendly.utils.DateTimeDeserializer;
import calendly.calendly.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

/**
 * ListActivityLog200ApplicationJSON - Activity log response
 */
public class ListActivityLog200ApplicationJSON {
    /**
     * The set of activity log entries matching the criteria
     */
    @JsonProperty("collection")
    public calendly.calendly.models.shared.Entry[] collection;
    public ListActivityLog200ApplicationJSON withCollection(calendly.calendly.models.shared.Entry[] collection) {
        this.collection = collection;
        return this;
    }
    
    /**
     * If there are more search results than the total_count field indicates, pagination will continue to return results past the total_count field value.
     */
    @JsonProperty("exceeds_max_total_count")
    public Boolean exceedsMaxTotalCount;
    public ListActivityLog200ApplicationJSON withExceedsMaxTotalCount(Boolean exceedsMaxTotalCount) {
        this.exceedsMaxTotalCount = exceedsMaxTotalCount;
        return this;
    }
    
    /**
     * The date and time of the newest entry (format: "2020-01-02T03:04:05.678Z") in the collection array.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("last_event_time")
    public OffsetDateTime lastEventTime;
    public ListActivityLog200ApplicationJSON withLastEventTime(OffsetDateTime lastEventTime) {
        this.lastEventTime = lastEventTime;
        return this;
    }
    
    @JsonProperty("pagination")
    public calendly.calendly.models.shared.Pagination pagination;
    public ListActivityLog200ApplicationJSON withPagination(calendly.calendly.models.shared.Pagination pagination) {
        this.pagination = pagination;
        return this;
    }
    
    /**
     * Total number of records based on search criteria
     */
    @JsonProperty("total_count")
    public Long totalCount;
    public ListActivityLog200ApplicationJSON withTotalCount(Long totalCount) {
        this.totalCount = totalCount;
        return this;
    }
    
}
