/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListOrganizationMemberships200ApplicationJSON - Service response
 */
public class ListOrganizationMemberships200ApplicationJSON {
    @JsonProperty("collection")
    public calendly.calendly.models.shared.OrganizationMembership[] collection;
    public ListOrganizationMemberships200ApplicationJSON withCollection(calendly.calendly.models.shared.OrganizationMembership[] collection) {
        this.collection = collection;
        return this;
    }
    
    @JsonProperty("pagination")
    public calendly.calendly.models.shared.Pagination pagination;
    public ListOrganizationMemberships200ApplicationJSON withPagination(calendly.calendly.models.shared.Pagination pagination) {
        this.pagination = pagination;
        return this;
    }
    
}
