/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import java.net.http.HttpResponse;

public class ListRoutingFormsResponse {
    
    public String contentType;
    public ListRoutingFormsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Request is not valid
     */
    
    public ListRoutingFormsErrorResponse errorResponse;
    public ListRoutingFormsResponse withErrorResponse(ListRoutingFormsErrorResponse errorResponse) {
        this.errorResponse = errorResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public ListRoutingFormsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public ListRoutingFormsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public ListRoutingForms200ApplicationJSON listRoutingForms200ApplicationJSONObject;
    public ListRoutingFormsResponse withListRoutingForms200ApplicationJSONObject(ListRoutingForms200ApplicationJSON listRoutingForms200ApplicationJSONObject) {
        this.listRoutingForms200ApplicationJSONObject = listRoutingForms200ApplicationJSONObject;
        return this;
    }
    
}
