/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import java.net.http.HttpResponse;

public class MeResponse {
    
    public String contentType;
    public MeResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Cannot authenticate caller
     */
    
    public MeErrorResponse errorResponse;
    public MeResponse withErrorResponse(MeErrorResponse errorResponse) {
        this.errorResponse = errorResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public MeResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public MeResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public Me200ApplicationJSON me200ApplicationJSONObject;
    public MeResponse withMe200ApplicationJSONObject(Me200ApplicationJSON me200ApplicationJSONObject) {
        this.me200ApplicationJSONObject = me200ApplicationJSONObject;
        return this;
    }
    
}
