/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PostSchedulingLinksRequestBodyMaxEventCountEnum - The max number of events that can be scheduled using this scheduling link.
 */
public enum PostSchedulingLinksRequestBodyMaxEventCountEnum {
    ONE("1");

    @JsonValue
    public final String value;

    private PostSchedulingLinksRequestBodyMaxEventCountEnum(String value) {
        this.value = value;
    }
}
