/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PostOrganizationsUuidInvitations201ApplicationJSON - Created
 */
public class PostOrganizationsUuidInvitations201ApplicationJSON {
    /**
     * Organization Invitation object
     */
    @JsonProperty("resource")
    public calendly.calendly.models.shared.OrganizationInvitation resource;
    public PostOrganizationsUuidInvitations201ApplicationJSON withResource(calendly.calendly.models.shared.OrganizationInvitation resource) {
        this.resource = resource;
        return this;
    }
    
}
