/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class PostOrganizationsUuidInvitationsRequestBody {
    /**
     * The email of the user being invited
     */
    @JsonProperty("email")public String email;
    public PostOrganizationsUuidInvitationsRequestBody withEmail(String email) {
        this.email = email;
        return this;
    }
    
}
