/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PostUsersUuidWebhooks201ApplicationJSON - Created
 */
public class PostUsersUuidWebhooks201ApplicationJSON {
    /**
     * Webhook Subscription Object
     */
    @JsonProperty("resource")
    public calendly.calendly.models.shared.WebhookSubscription resource;
    public PostUsersUuidWebhooks201ApplicationJSON withResource(calendly.calendly.models.shared.WebhookSubscription resource) {
        this.resource = resource;
        return this;
    }
    
}
