/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import calendly.calendly.utils.SpeakeasyMetadata;

public class PostScheduledEventsUuidCancellationRawRequest {
    public PostScheduledEventsUuidCancellationPathParams pathParams;
    public PostScheduledEventsUuidCancellationRawRequest withPathParams(PostScheduledEventsUuidCancellationPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
    /**
     * Optional cancellation reason.
     */
    @SpeakeasyMetadata("request:mediaType=application/xml")public byte[] request;
    public PostScheduledEventsUuidCancellationRawRequest withRequest(byte[] request) {
        this.request = request;
        return this;
    }
    
}
