/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PostSharesRequestBodyAvailabilityRuleRulesWdayEnum - is required when `type` is 'wday'
 */
public enum PostSharesRequestBodyAvailabilityRuleRulesWdayEnum {
    SUNDAY("sunday"),
    MONDAY("monday"),
    TUESDAY("tuesday"),
    WEDNESDAY("wednesday"),
    THURSDAY("thursday"),
    FRIDAY("friday"),
    SATURDAY("saturday");

    @JsonValue
    public final String value;

    private PostSharesRequestBodyAvailabilityRuleRulesWdayEnum(String value) {
        this.value = value;
    }
}
