/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PostUsersUuidWebhooksRequestBodyScopeEnum - Indicates if the webhook subscription scope will be "organization" or "user"
 */
public enum PostUsersUuidWebhooksRequestBodyScopeEnum {
    ORGANIZATION("organization"),
    USER("user");

    @JsonValue
    public final String value;

    private PostUsersUuidWebhooksRequestBodyScopeEnum(String value) {
        this.value = value;
    }
}
