/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PostSchedulingLinks201ApplicationJSON - Created
 */
public class PostSchedulingLinks201ApplicationJSON {
    @JsonProperty("resource")public PostSchedulingLinks201ApplicationJSONResource resource;
    public PostSchedulingLinks201ApplicationJSON withResource(PostSchedulingLinks201ApplicationJSONResource resource) {
        this.resource = resource;
        return this;
    }
    
}
