/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import calendly.calendly.utils.SpeakeasyMetadata;

public class PostScheduledEventsUuidCancellationJsonRequest {
    /**
     * Optional cancellation reason.
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public PostScheduledEventsUuidCancellationApplicationJSON requestBody;
    public PostScheduledEventsUuidCancellationJsonRequest withRequestBody(PostScheduledEventsUuidCancellationApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * The event's unique indentifier
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=uuid")
    public String uuid;
    public PostScheduledEventsUuidCancellationJsonRequest withUuid(String uuid) {
        this.uuid = uuid;
        return this;
    }
    
}
