/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import calendly.calendly.utils.SpeakeasyMetadata;

public class PostScheduledEventsUuidCancellationJsonRequest {
    public PostScheduledEventsUuidCancellationPathParams pathParams;
    public PostScheduledEventsUuidCancellationJsonRequest withPathParams(PostScheduledEventsUuidCancellationPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
    /**
     * Optional cancellation reason.
     */
    @SpeakeasyMetadata("request:mediaType=application/json")public PostScheduledEventsUuidCancellationApplicationJSON request;
    public PostScheduledEventsUuidCancellationJsonRequest withRequest(PostScheduledEventsUuidCancellationApplicationJSON request) {
        this.request = request;
        return this;
    }
    
}
