/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import calendly.calendly.utils.SpeakeasyMetadata;

public class PostScheduledEventsUuidCancellationMultipartRequest {
    /**
     * Optional cancellation reason.
     */
    @SpeakeasyMetadata("request:mediaType=multipart/form-data")
    public java.util.Map<String, Object> requestBody;
    public PostScheduledEventsUuidCancellationMultipartRequest withRequestBody(java.util.Map<String, Object> requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * The event's unique indentifier
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=uuid")
    public String uuid;
    public PostScheduledEventsUuidCancellationMultipartRequest withUuid(String uuid) {
        this.uuid = uuid;
        return this;
    }
    
}
