/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import calendly.calendly.utils.SpeakeasyMetadata;

public class PostScheduledEventsUuidCancellationRawRequest {
    /**
     * Optional cancellation reason.
     */
    @SpeakeasyMetadata("request:mediaType=application/xml")
    public byte[] requestBody;
    public PostScheduledEventsUuidCancellationRawRequest withRequestBody(byte[] requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * The event's unique indentifier
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=uuid")
    public String uuid;
    public PostScheduledEventsUuidCancellationRawRequest withUuid(String uuid) {
        this.uuid = uuid;
        return this;
    }
    
}
