/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PostSchedulingLinks201ApplicationJSONResourceOwnerTypeEnum - Resource type (currently, this is always EventType)
 */
public enum PostSchedulingLinks201ApplicationJSONResourceOwnerTypeEnum {
    EVENT_TYPE("EventType");

    @JsonValue
    public final String value;

    private PostSchedulingLinks201ApplicationJSONResourceOwnerTypeEnum(String value) {
        this.value = value;
    }
}
