/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import calendly.calendly.utils.SpeakeasyMetadata;

public class PostOrganizationsUuidInvitationsRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public PostOrganizationsUuidInvitationsRequestBody requestBody;
    public PostOrganizationsUuidInvitationsRequest withRequestBody(PostOrganizationsUuidInvitationsRequestBody requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * The organization's unique identifier
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=uuid")
    public String uuid;
    public PostOrganizationsUuidInvitationsRequest withUuid(String uuid) {
        this.uuid = uuid;
        return this;
    }
    
}
