/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class PostUsersUuidWebhooksRequestBody {
    /**
     * List of user events to subscribe to.
     */
    @JsonProperty("events")
    public PostUsersUuidWebhooksRequestBodyEventsEnum[] events;
    public PostUsersUuidWebhooksRequestBody withEvents(PostUsersUuidWebhooksRequestBodyEventsEnum[] events) {
        this.events = events;
        return this;
    }
    
    /**
     * The unique reference to the organization that the webhook will be tied to.
     */
    @JsonProperty("organization")
    public String organization;
    public PostUsersUuidWebhooksRequestBody withOrganization(String organization) {
        this.organization = organization;
        return this;
    }
    
    /**
     * Indicates if the webhook subscription scope will be "organization" or "user"
     */
    @JsonProperty("scope")
    public PostUsersUuidWebhooksRequestBodyScopeEnum scope;
    public PostUsersUuidWebhooksRequestBody withScope(PostUsersUuidWebhooksRequestBodyScopeEnum scope) {
        this.scope = scope;
        return this;
    }
    
    /**
     * Optional secret key shared between your application and Calendly. See https://developer.calendly.com/api-docs/ZG9jOjM2MzE2MDM4-webhook-signatures for additional information.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("signing_key")
    public String signingKey;
    public PostUsersUuidWebhooksRequestBody withSigningKey(String signingKey) {
        this.signingKey = signingKey;
        return this;
    }
    
    /**
     * The URL where you want to receive POST requests for events you are subscribed to.
     */
    @JsonProperty("url")
    public String url;
    public PostUsersUuidWebhooksRequestBody withUrl(String url) {
        this.url = url;
        return this;
    }
    
    /**
     * The unique reference to the user that the webhook will be tied to.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("user")
    public String user;
    public PostUsersUuidWebhooksRequestBody withUser(String user) {
        this.user = user;
        return this;
    }
    
}
