/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PostShares201ApplicationJSON - Created
 */
public class PostShares201ApplicationJSON {
    @JsonProperty("resource")
    public calendly.calendly.models.shared.Share resource;
    public PostShares201ApplicationJSON withResource(calendly.calendly.models.shared.Share resource) {
        this.resource = resource;
        return this;
    }
    
}
