/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PostInviteeNoShow201ApplicationJSON - Created
 */
public class PostInviteeNoShow201ApplicationJSON {
    /**
     * Information about an invitees no show.
     */
    @JsonProperty("resource")
    public calendly.calendly.models.shared.InviteeNoShow resource;
    public PostInviteeNoShow201ApplicationJSON withResource(calendly.calendly.models.shared.InviteeNoShow resource) {
        this.resource = resource;
        return this;
    }
    
}
