/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package calendly.calendly.models.operations;



public class RevokeUsersOrganizationInvitationRequest {
    public RevokeUsersOrganizationInvitationPathParams pathParams;
    public RevokeUsersOrganizationInvitationRequest withPathParams(RevokeUsersOrganizationInvitationPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
}
